### PR TITLE
Some style changes.

### PR DESCRIPTION
**Pull request by ghost**
Made search bar follow while scrolling, and it doesn't extend into the sidebar.

### CODE REVIEW

**Comment by ocboogie** [comment]
The extending into the sidebar was purposeful, in my opinion it looks better. I'm happy having the navbar follow though

**Comment by ghost** [comment]
Ok cool, I put that back.
edit: Also I added some bottom padding which allows you to scroll down a little further.

**Comment by ocboogie** [comment]
And preferably we don't use flexbox because of its poor support, And it doesn't seem to have a use here, because `margin: auto` should center it. And the sidebar should be a fixed size, not relative to the browser size. And the height of the navbar shouldn't be a fixed size.
I think all we really need for the fixed navbar is:
```css
/* Navbar.vue */
position: fixed;
width: 100%;

/* Some color. I'm not sure about this one */
background-color: rgba(43, 44, 57, 0.95);
/* App.vue */
padding-top: 7rem;
```
The reason for having the padding-top in `App.vue` is it's not the Items component's responsibility to play nice with the navbar. It should work on it's own

**Comment by ocboogie** [comment]
And if you have any disagreements please voice them.

**Comment by ghost** [comment]
I think your points are valid, I'm happy to apply them. There is one problem though. With position: fixed, the Items div gets put snug behind the navbar. Whereas before it rested below it. Putting padding in App.vue pushes the navbar down as well. Meaning we'd have to do something like margin-top: -\<padding> to account for that. Hopefully that makes sense, any opinions?

**Comment by ghost** [comment]
Also, for margin: auto to work, according to [this link](http://www.tipue.com/blog/center-a-div/), "The inner div must have a width and height property. This doesn't work if the outer div has a fixed height. " So, we would need top and bottom padding in the navbar around the search input. Then it become kind of a hassle to calculate how far the Items need to be to sit below the navbar correctly.

**Comment by ghost** [comment]
As for flexbox support, mdn says "[Browser support for flexbox is excellent](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox#Status_in_browsers)". However if you want to avoid it that's cool.

**Comment by ocboogie** [comment]
I don't really mind using flexbox but sense the website hasn't needed it so far it would be nice to stay without for now at least. 
Also I meant to type:
```vue
// App.vue
.items {
  padding-top: 7rem;
}
```

**Comment by ocboogie** [comment]
And actually it might be better to have the `position: fixed`  and `width: 100%` for the navbar in App.vue, sense it's not navbar's responsibility to be placed correctly in the page

**Comment by ocboogie** [comment]
I tried the code I sent earlier but with the items selector fixed in `App.vue`  and it worked, not sure if it would work in other browsers but I don't see why not

**Comment by ghost** [comment]
Check out my recent update, how's all that look?

**Comment by ocboogie** [comment]
I'll have to test this on my computer and I won't be home until tomorrow. Sorry for the delay.

**Comment by ocboogie** [comment]
Sorry, for the delay. I've been testing some other frameworks. And I'm probably going to do a layout overhaul soon, so these changes will be redundant

**Comment by ghost** [comment]
Cool no worries. Interested in what you're going in to next.

**Pull request closed without merging**
