### PR TITLE
Sort fix

### PR DESCRIPTION
**Pull request by ghost**
The sort function wasn't working right sometimes, this seems to fix it.

### CODE REVIEW

**Comment by ocboogie** [comment]
What do you mean by sometimes, shouldn't it be the same every time?
Or do you mean in some areas and if so, where?

**Comment by ghost** [comment]
In Firefox the I was seeing this: https://i.imgur.com/SxBo7TR.jpg
In Chrome it seemed to come back fine. I'm not certain why, maybe due to implementation differences between browsers.

This line seemed to be the culprit: `if (!b.isLunar && a.isLunar) {`
It doesn't account for the scenario where `b` is lunar and `a` is not. In that case it would fall back to `index` comparison.

**Comment by ocboogie** [comment]
Yeah, that sorting function was kinda a mess. Now that you pointed out it does seem flawed, but it's odd that it works in Chrome, IE and not Firefox. Anyways I'll merge it. Thanks!

**Comment by ghost** [comment]
Yeah very odd indeed. Thanks!

**Pull request merged**
